### PR TITLE
Refactor storyboard

### PR DESCRIPTION
**Pull request by manas15**
To keep things organized I have divided things into 4 storyboards. 
1. Main Storyboard:  Will have the tabbar viewcontroller 
2. Pages: For the First tab
3. Info: For the information tab
4. Trip: For PlanTrip tab

### CODE REVIEW

**Comment by bphenriques** [comment]
Everything looks fine :)

However, I can't accept with this issue:
screen shot 2016-03-06 at 11 55 28

**Comment by bphenriques** [comment]
Also: 
https://github.com/manas15/malaria-app-ios/blob/RefactorStoryboard/malaria-ios/ViewControllers/PlanTrip/PlanTripViewController.swift#L124

https://github.com/manas15/malaria-app-ios/blob/RefactorStoryboard/malaria-ios/ViewControllers/PlanTrip/PlanTripViewController.swift#L143

**Comment by manas15** [comment]
Mark Comments are removed and the tab bar image bug is now fixed. Try running the last commit.

**Comment by bphenriques** [comment]
Simpler mark:
`// MARK: - UITableViewDataSource`

I will check now.

**Comment by manas15** [comment]
Sure.

**Comment by bphenriques** [comment]
You bumbed the deployment target to 9.0 (I think you wanted to change the base SDK) and the app must be compatible with 8.4 to support older devices. 

You have to test the app as well on 8.4 devices (I tried to run and the code does not compile).

**Comment by bphenriques** [comment]
Put deployment target 8.0 (the original)

**Comment by manas15** [comment]
Storyboard references required an app targeting at least iOS 9.0, OS X 10.11, or WatchKit 2.0 for watchOS. In the release notes of xcode 7.2 it is mentioned that Backwards compatible relationship segues (ie. compatible with iOS8.0) can't be relationship segues (ie. view controllers in tab bar controller). 
For the same reason we have to have a minimum of 9.0 as the build target to have RefactorStoryboard.

**Comment by bphenriques** [comment]
Bah. I understand. We will address this issue later then since we do not want to lose iOS 8.X users :)

**Comment by manas15** [comment]
Yeah, I think you are right. Lets wait and see if apple comes out with some solution for this problem. Till then lets concentrate on other issues. :)

**Pull request closed without merging**
