### PR TITLE
Added swipe posts

### PR DESCRIPTION
**Pull request by mahmoudashraf93**

### CODE REVIEW

**Comment by bphenriques** [comment]
The server is offline. How did you test?

**Comment by mahmoudashraf93** [comment]
i tested by the available Posts Array

**Comment by bphenriques** [comment]
Was the array of Posts empty? The server is not responding correctly therefore I assume it is.

**Comment by bphenriques** [comment]
"Couldn't update Peace Corps messages"

**Comment by bphenriques** [comment]
On 8.X it works fine. The iOS 9.X is a different issue.

It works fine ( :) ) but I will ask you to remove the excessive newlines before I accept:
https://github.com/mahmoudashraf93/malaria-app-ios/blob/develop/malaria-ios/ViewControllers/InfoHub/PostDetailedViewController.swift#L48

Is your xcode doing that automatically?

**Comment by mahmoudashraf93** [comment]
Removed them :)

**Comment by bphenriques** [comment]
Remove print and clean conditions:
if (send.direction == .Right && currentIndex > 0)

**Pull request merged**
