### PR TITLE
Swift alternative

### PR DESCRIPTION
**Pull request by bphenriques**
Swift 2 and iOS 9 compatible

Some dependencies from Podfile had to be handled differently:
- Charts: the compatible version is on branch master and it is not yet public therefore a direct link to the github page was used;
- CVCalendar: There is still this issue: https://github.com/systers/malaria-app-ios/issues/15 therefore a fork was made and adapted;
- Alamofire and SwiftyJSON was straightforward;
- The remaining pods were created by me and I updated to swift 2.0 accordingly and everything seems ok.

I also added some few NSDate extensions that might be useful (with the according unit tests).

### CODE REVIEW

**Comment by rosariorobinson** [comment]
@bphenriques @kangaroo5383 is this ready to merge?

**Comment by bphenriques** [comment]
In my opinion, yes. Only the issue server side remains.

**Comment by bphenriques** [comment]
@rosariorobinson 
Hello, any updates on this? :)

**Comment by Vedrana** [comment]
Merging this for the GHC Open Source Day.

**Pull request merged**
