### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by 123cristen**
Other updated files were changed when updating docs and pods

### CODE REVIEW

**Comment by Vedrana** [comment]
@bphenriques Hey Bruno, could you take a quick look at this pull req, I wasn't sure if it's okay to update the docs. I'm guessing yes, but it'd be great if you could confirm. Thank you!

**Comment by bphenriques** [comment]
@Vedrana 
The docs are auto-generated. Therefore I assume that everything is ok (the doc generator SW must have been updated meanwhile to support swift 2). Regarding the rest, it is green light for me.

I would gladly accept the pull req, however, I am not the one who accepts the pull-requests. Usually is @shanusalunke or @kangaroo5383 or @rosariorobinson . I would gladly do so if I had the permission. If so I accept right away.

**Comment by rosariorobinson** [comment]
Is this for the doc updates?

**Comment by Vedrana** [comment]
@bphenriques Cool, thanks!
I was granted the magical powers to merge pull requests for Malaria iOS during the GHC open source day, and while I won't abuse them, I'll go ahead and merge this one.

@123cristen Congrats on your first Malaria contribution! ✨

**Comment by Vedrana** [comment]
@rosariorobinson Yes, this is adding info on potential missing pods in the XCode project config to README, and just refreshing automatically generated code docs.

**Comment by rosariorobinson** [comment]
ok, thanks.

**Comment by 123cristen** [comment]
Thanks @Vedrana! Exciting to contribute!

**Pull request merged**
